version: '3.9'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      FLASK_PORT: 8000
      FLASK_DEBUG: "True"
    networks:
      - mlflow-network
    depends_on:
      - mlflow
    command: python app.py

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    command: mlflow server --host 0.0.0.0 --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlflow/mlruns
    volumes:
      - ./mlruns:/mlflow/mlruns
      - ./mlflow.db:/mlflow/mlflow.db
    networks:
      - mlflow-network

networks:
  mlflow-network:
    driver: bridge